# Generated by Django 5.2 on 2025-05-22 14:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBibliotheque', '0004_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.AlterModelOptions(
            name='emprunter',
            options={'ordering': ['-date_demande'], 'verbose_name': 'Emprunt', 'verbose_name_plural': 'Emprunts'},
        ),
        migrations.RenameField(
            model_name='emprunter',
            old_name='date_retour',
            new_name='date_retour_prevue',
        ),
        migrations.AddField(
            model_name='emprunter',
            name='date_demande',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprunter',
            name='date_retour_reel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprunter',
            name='duree_jours',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='emprunter',
            name='notes_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprunter',
            name='notes_utilisateur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprunter',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('rendu', 'Rendu'), ('en_retard', 'En retard')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='etat',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('bon', 'Bon'), ('acceptable', 'Acceptable'), ('mauvais', 'Mauvais')], default='excellent', max_length=20),
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='numero_exemplaire',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livre',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprunter',
            name='date_emprunt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprunter',
            name='exemplaire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emprunt_actuel', to='appBibliotheque.exemplaire'),
        ),
        migrations.RemoveField(
            model_name='livre',
            name='categories',
        ),
        migrations.AlterField(
            model_name='livre',
            name='date_publication',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='livre',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='exemplaire',
            unique_together={('livre', 'numero_exemplaire')},
        ),
        migrations.AddField(
            model_name='livre',
            name='categories',
            field=models.ManyToManyField(related_name='livres', to='appBibliotheque.categorie'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('notifie', models.BooleanField(default=False)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='appBibliotheque.livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_reservation'],
                'unique_together': {('livre', 'utilisateur')},
            },
        ),
    ]
