# Generated by Django 5.2 on 2025-06-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBibliotheque', '0005_categorie_alter_emprunter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunter',
            name='est_retourne',
            field=models.BooleanField(default=False),
        ),
    ]
